version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
jobs:
  release:
    executor: cypress/base-14
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run semantic-release
workflows:
  build:
    jobs:
      - cypress/run:
          post-install:
            - run: apt-get update
            - run: apt-get install -y libgbm-dev
          executor: cypress/browsers-chrome69
          browser: chrome
      - release:
          requires:
            - cypress/run
